name: PlatformIO CI

on: 
  push:
    branches: 
      - dev

jobs:
  pio-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1.0.1    
  
      - name: Run PlatformIO
        run: pio run -e kegmon-release -e kegmon32s2-release

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version. https://github.com/marketplace/actions/add-commit
        with:
          add: 'bin'
          author_name: GitHub Action
          author_email: mp-se@noreply.github.com
          branch: dev
          default_author: github_actor
          message: 'GitHub Action Build'
          pathspec_error_handling: ignore
